# Generated by Django 5.2.4 on 2025-08-14 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('width', models.CharField(blank=True, help_text='Width dimension', max_length=50)),
                ('height', models.CharField(blank=True, help_text='Height dimension', max_length=50)),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('rustic', 'Rustic'), ('scandinavian', 'Scandinavian')], max_length=20)),
                ('deadline', models.DateField(blank=True, help_text='Preferred completion date', null=True)),
                ('budget', models.CharField(blank=True, choices=[('under-500', 'Under €500'), ('500-1000', '€500 - €1,000'), ('1000-2500', '€1,000 - €2,500'), ('2500-5000', '€2,500 - €5,000'), ('over-5000', 'Over €5,000')], max_length=20)),
                ('additional', models.TextField(blank=True, help_text='Additional requirements or notes')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both Email & Phone')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price for the custom request', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin user assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Request',
                'verbose_name_plural': 'Custom Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
