# Generated by Django 5.2.4 on 2025-08-14 23:54

import django.db.models.deletion
import furniture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_customrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, help_text='Client name (optional)', max_length=100)),
                ('project_date', models.DateField(blank=True, help_text='When the project was completed', null=True)),
                ('location', models.CharField(blank=True, help_text='Project location', max_length=200)),
                ('materials_used', models.CharField(blank=True, max_length=300)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, choices=[('under-1000', 'Under €1,000'), ('1000-5000', '€1,000 - €5,000'), ('5000-10000', '€5,000 - €10,000'), ('10000-25000', '€10,000 - €25,000'), ('over-25000', 'Over €25,000')], max_length=50)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured projects')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_projects', to='furniture.gallerycategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('gallery_category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=furniture.models.gallery_image_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for the project')),
                ('is_before_image', models.BooleanField(default=False, help_text='Before/after comparison')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='furniture.galleryproject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['gallery_project', 'is_primary'], name='furniture_g_gallery_c392c4_idx')],
            },
        ),
    ]
