# Generated by Django 5.2.4 on 2025-08-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('furniture', '0003_gallerycategory_galleryproject_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=5)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'language_code'], name='furniture_t_content_4011e4_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'language_code')},
            },
        ),
    ]
